# Generated by Django 4.1.1 on 2022-09-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_geom_keypoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geom',
            name='keypoints',
            field=models.TextField(default='', max_length=20000),
        ),
    ]
