# Generated by Django 4.1.1 on 2022-09-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_geom_keypoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('keypoint', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Флаги',
                'verbose_name_plural': 'Флаги',
            },
        ),
        migrations.AlterModelOptions(
            name='geom',
            options={'verbose_name': 'История', 'verbose_name_plural': 'История'},
        ),
    ]
