# Generated by Django 4.1.1 on 2022-09-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_flags_alter_geom_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='geom',
            name='ids',
            field=models.IntegerField(default=0),
        ),
    ]
