# Generated by Django 4.1.1 on 2022-09-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_geom_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField(default=0)),
                ('points', models.TextField(default='', max_length=20000)),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршрут',
            },
        ),
        migrations.AddField(
            model_name='geom',
            name='keypointsplaned',
            field=models.TextField(default='', max_length=20000),
        ),
    ]
