# Generated by Django 4.1.1 on 2022-10-09 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_geom_date_geom_datekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geom',
            name='datekey',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 12, 48, 30, 214638)),
        ),
    ]
