# Generated by Django 4.1.1 on 2022-10-09 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_geom_datekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='geom',
            name='datekeys',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 12, 52, 46, 107225)),
        ),
        migrations.AlterField(
            model_name='geom',
            name='datekey',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 12, 52, 46, 107225)),
        ),
    ]
