# Generated by Django 4.1.1 on 2022-10-09 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_geom_datekeys_alter_geom_datekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geom',
            name='datekeys',
        ),
        migrations.AlterField(
            model_name='geom',
            name='datekey',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 12, 53, 22, 752136)),
        ),
    ]
