# Generated by Django 4.1.1 on 2022-10-09 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_geom_datekeys_alter_geom_datekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='geom',
            name='Температура',
            field=models.IntegerField(default=-273),
        ),
        migrations.AlterField(
            model_name='geom',
            name='datekey',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 12, 59, 49, 462500)),
        ),
    ]
