# Generated by Django 4.1.1 on 2022-10-09 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_geom_температура_alter_geom_datekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geom',
            name='datekey',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 13, 0, 43, 217880)),
        ),
        migrations.AlterField(
            model_name='geom',
            name='Температура',
            field=models.FloatField(default=-273.15),
        ),
    ]
