# Generated by Django 4.1.1 on 2022-10-09 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_geom_datekey_alter_geom_температура'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geom',
            name='datekey',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 13, 1, 5, 969935)),
        ),
        migrations.AlterField(
            model_name='geom',
            name='Температура',
            field=models.FloatField(default='-273.15'),
        ),
    ]
