# Generated by Django 4.1.1 on 2022-10-09 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_geom_datekey_alter_geom_температура'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geom',
            name='Температура',
        ),
        migrations.AddField(
            model_name='geom',
            name='Температура(ы)',
            field=models.CharField(default='-273.15', max_length=20000),
        ),
        migrations.AlterField(
            model_name='geom',
            name='datekey',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 13, 6, 50, 635078)),
        ),
    ]
