# Generated by Django 4.1.1 on 2022-10-09 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_geom_температура_geom_температура(ы)_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geom',
            name='Температура(ы)',
        ),
        migrations.AlterField(
            model_name='geom',
            name='datekey',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 13, 13, 35, 570302)),
        ),
    ]
