# Generated by Django 4.1.1 on 2022-10-10 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_geom_температура(ы)_alter_geom_datekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='geom',
            name='numpoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='numpoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='geom',
            name='datekey',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 19, 18, 9, 452776)),
        ),
    ]
