# Generated by Django 4.1.1 on 2022-10-10 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_geom_numpoints_route_numpoints_alter_geom_datekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='numpoints',
        ),
        migrations.AlterField(
            model_name='geom',
            name='datekey',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 19, 21, 27, 644731)),
        ),
    ]
