# Generated by Django 4.1.1 on 2022-10-10 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_route_numpoints_alter_geom_datekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='geom',
            name='numpointspl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='geom',
            name='datekey',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 19, 22, 21, 599368)),
        ),
    ]
